#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rubocop
Version  : 0.32.0
Release  : 8
URL      : https://rubygems.org/downloads/rubocop-0.32.0.gem
Source0  : https://rubygems.org/downloads/rubocop-0.32.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-rubocop-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec

%description
[![Gem Version](https://badge.fury.io/rb/rubocop.svg)](http://badge.fury.io/rb/rubocop)
[![Dependency Status](https://gemnasium.com/bbatsov/rubocop.svg)](https://gemnasium.com/bbatsov/rubocop)
[![Build Status](https://travis-ci.org/bbatsov/rubocop.svg?branch=master)](https://travis-ci.org/bbatsov/rubocop)
[![Coverage Status](http://img.shields.io/coveralls/bbatsov/rubocop/master.svg)](https://coveralls.io/r/bbatsov/rubocop)
[![Code Climate](https://codeclimate.com/github/bbatsov/rubocop/badges/gpa.svg)](https://codeclimate.com/github/bbatsov/rubocop)
[![Inline docs](http://inch-ci.org/github/bbatsov/rubocop.svg)](http://inch-ci.org/github/bbatsov/rubocop)
[![Gratipay](http://img.shields.io/gratipay/bbatsov.svg)](https://www.gratipay.com/bbatsov/)

%package bin
Summary: bin components for the rubygem-rubocop package.
Group: Binaries

%description bin
bin components for the rubygem-rubocop package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rubocop-0.32.0
gem spec %{SOURCE0} -l --ruby > rubygem-rubocop.gemspec

%build
gem build rubygem-rubocop.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rubocop-0.32.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rubocop-0.32.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/assets/logo.png
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/assets/output.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/bin/rubocop
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/config/default.yml
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/config/disabled.yml
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/config/enabled.yml
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/comment_config.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/config_loader.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/config_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/autocorrect_logic.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/commissioner.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/cop.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/corrector.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/force.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/ignored_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/ambiguous_operator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/ambiguous_regexp_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/assignment_in_condition.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/block_alignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/condition_position.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/debugger.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/def_end_alignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/deprecated_class_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/duplicate_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/each_with_object_argument.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/else_layout.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/empty_ensure.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/empty_interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/end_alignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/end_in_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/ensure_return.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/eval.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/handle_exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/invalid_character_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/literal_in_condition.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/literal_in_interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/loop.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/nested_method_definition.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/non_local_exit_from_iterator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/parentheses_as_grouped_expression.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/require_parentheses.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/rescue_exception.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/shadowing_outer_local_variable.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/space_before_first_arg.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/string_conversion_in_interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/syntax.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/underscore_prefixed_variable_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/unneeded_disable.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/unreachable_code.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/unused_block_argument.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/unused_method_argument.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/useless_access_modifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/useless_assignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/useless_comparison.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/useless_else_without_rescue.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/useless_setter_call.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/lint/void.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/abc_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/block_nesting.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/class_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/cyclomatic_complexity.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/line_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/method_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/module_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/parameter_lists.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/metrics/perceived_complexity.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/access_modifier_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/annotation_comment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/array_syntax.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/autocorrect_alignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/autocorrect_unless_changing_ast.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/check_assignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/classish_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/code_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/configurable_enforced_style.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/configurable_max.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/configurable_naming.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/empty_lines_around_body.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/end_keyword_alignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/if_node.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/method_complexity.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/min_body_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/negative_conditional.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/on_method_def.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/on_normal_if_unless.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/parser_diagnostic.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/percent_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/safe_assignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/space_after_punctuation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/space_before_punctuation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/space_inside.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/statement_modifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/string_help.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/string_literals_help.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/surrounding_space.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/mixin/unused_argument.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/offense.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/performance/count.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/performance/detect.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/performance/flat_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/performance/reverse_each.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/performance/sample.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/performance/size.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/action_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/default_scope.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/delegate.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/find_by.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/find_each.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/has_and_belongs_to_many.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/output.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/read_write_attribute.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/scope_args.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/time_zone.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/rails/validation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/severity.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/access_modifier_indentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/accessor_method_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/alias.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/align_array.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/align_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/align_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/and_or.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/array_join.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/ascii_comments.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/ascii_identifiers.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/attr.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/auto_resource_cleanup.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/bare_percent_literals.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/begin_block.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/block_comments.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/block_delimiters.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/block_end_newline.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/braces_around_hash_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/case_equality.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/case_indentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/character_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/class_and_module_camel_case.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/class_and_module_children.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/class_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/class_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/class_vars.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/closing_parenthesis_indentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/collection_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/colon_method_call.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/command_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/comment_annotation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/comment_indentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/constant_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/copyright.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/def_with_parentheses.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/deprecated_hash_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/documentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/dot_position.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/double_negation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/each_with_object.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/else_alignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_else.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_line_between_defs.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_lines.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_lines_around_access_modifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_lines_around_block_body.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_lines_around_class_body.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_lines_around_method_body.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_lines_around_module_body.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/empty_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/end_block.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/end_of_line.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/even_odd.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/extra_spacing.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/file_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/first_parameter_indentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/flip_flop.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/for.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/format_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/global_vars.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/guard_clause.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/hash_syntax.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/if_unless_modifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/if_with_semicolon.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/indent_array.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/indent_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/indentation_consistency.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/indentation_width.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/infinite_loop.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/inline_comment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/lambda.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/lambda_call.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/leading_comment_space.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/line_end_concatenation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/method_call_parentheses.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/method_called_on_do_end_block.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/method_def_parentheses.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/method_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/missing_else.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/module_function.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/multiline_block_chain.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/multiline_block_layout.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/multiline_if_then.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/multiline_operation_indentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/multiline_ternary_operator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/negated_if.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/negated_while.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/nested_ternary_operator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/next.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/nil_comparison.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/non_nil_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/not.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/numeric_literals.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/one_line_conditional.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/op_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/parallel_assignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/parentheses_around_condition.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/percent_literal_delimiters.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/percent_q_literals.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/perl_backrefs.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/predicate_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/proc.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/raise_args.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/redundant_begin.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/redundant_exception.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/redundant_return.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/redundant_self.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/regexp_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/rescue_modifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/self_assignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/semicolon.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/signal_exception.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/single_line_block_params.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/single_line_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/single_space_before_first_arg.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_after_colon.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_after_comma.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_after_control_keyword.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_after_method_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_after_not.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_after_semicolon.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_around_block_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_around_equals_in_parameter_default.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_around_operators.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_before_block_braces.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_before_comma.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_before_comment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_before_modifier_keyword.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_before_semicolon.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_inside_block_braces.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_inside_brackets.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_inside_hash_literal_braces.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_inside_parens.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_inside_range_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/space_inside_string_interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/special_global_vars.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/string_literals.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/string_literals_in_interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/struct_inheritance.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/symbol_array.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/symbol_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/symbol_proc.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/tab.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/trailing_blank_lines.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/trailing_comma.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/trailing_underscore_variable.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/trailing_whitespace.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/trivial_accessors.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/unless_else.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/unneeded_capital_w.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/unneeded_percent_q.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/variable_interpolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/variable_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/when_then.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/while_until_do.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/while_until_modifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/style/word_array.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/team.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/util.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/variable_force.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/variable_force/assignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/variable_force/locatable.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/variable_force/reference.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/variable_force/scope.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/variable_force/variable.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/cop/variable_force/variable_table.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/base_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/clang_style_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/colorizable.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/disabled_config_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/disabled_lines_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/emacs_style_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/file_list_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/formatter_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/fuubar_style_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/html_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/json_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/offense_count_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/progress_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/simple_text_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/formatter/text_util.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/path_util.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/processed_source.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/rake_task.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/string_util.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/target_finder.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/token.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/lib/rubocop/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/logo/rubo-logo-horizontal.png
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/logo/rubo-logo-square.png
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/logo/rubo-logo-symbol.png
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.19.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.19.1.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.20.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.20.1.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.21.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.22.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.23.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.24.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.24.1.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.25.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.26.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.26.1.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.27.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.27.1.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.28.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.29.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.29.1.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.30.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.30.1.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.31.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/relnotes/v0.32.0.md
/usr/lib64/ruby/gems/2.3.0/gems/rubocop-0.32.0/rubocop.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/rubocop-0.32.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/rubocop
